resources:
- rbac.yaml
- service.yaml
- deployment.yaml
- istio.yaml

namespace: kserve

commonLabels:
  kustomize.component: kserve-models-web-app
  app.kubernetes.io/component: kserve-models-web-app

images:
- name: inf-repo-registry.cn-wulanchabu.cr.aliyuncs.com/infly/models-web-app
  newName: inf-repo-registry.cn-wulanchabu.cr.aliyuncs.com/infly/models-web-app
  newTag: v0.13.0-rc.0
configMapGenerator:
  - name: kserve-models-web-app-config
    literals:
    - APP_DISABLE_AUTH="True"
